config/routes.rb
Rails.application.routes.draw do 
    
  devise_for :users
  resources :users

  resources :transactions
  resources :investments
  resources :investment_types
  resources :brokers
  resources :transaction_types      
  resources :fundamental_info, only: %i[index new create destroy]

  get 'home/index'
  root to: "home#index"

end

app/models/investment.rb
class Investment < ApplicationRecord

  belongs_to :investment_type
  has_many :fundamental_infos

  after_initialize :set_default_country

  private

  def set_default_country
    self.country_code = 'BR' if country_code.blank? 
  end

end

app/models/investment_type.rb
class InvestmentType < ApplicationRecord
    validates :name, presence: true
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
    before_action :set_investment, only: %i[show edit update destroy]
   
    # GET /investments or /investments.json
    def index
      @investments = Investment.all
    end
   
    # GET /investments/1 or /investments/1.json
    def show; end
   
    # GET /investments/new
    def new
      @investment = Investment.new
    end
   
    # GET /investments/1/edit
    def edit; end
   
    # POST /investments or /investments.json
    def create
      @investment = Investment.new(investment_params)
   
      respond_to do |format|
        if @investment.save
          format.html { redirect_to @investment, notice: 'Investment was successfully created.' }
          format.json { render :show, status: :created, location: @investment }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @investment.errors, status: :unprocessable_entity }
        end
      end
    end
   
    # PATCH/PUT /investments/1 or /investments/1.json
    def update
      respond_to do |format|
        if @investment.update(investment_params)
          format.html { redirect_to @investment, notice: 'Investment was successfully updated.' }
          format.json { render :show, status: :ok, location: @investment }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @investment.errors, status: :unprocessable_entity }
        end
      end
    end
   
    # DELETE /investments/1 or /investments/1.json
    def destroy
      @investment.destroy
      respond_to do |format|
        format.html { redirect_to investments_url, notice: 'Investment was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
   
    private
   
    # Use callbacks to share common setup or constraints between actions.
    def set_investment
      @investment = Investment.find(params[:id])
    end
   
    # Only allow a list of trusted parameters through.
    def investment_params
      params.require(:investment).permit(:code, :name, :company, :cousntry_code, :investment_type_id)
    end
   end

app/views/investments/_form.html.erb
<%= form_with(model: investment, local: true) do |form| %>
 <% if investment.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(investment.errors.count, "error") %> prohibited this investment from being saved:</h2>

     <ul>
     <% investment.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
 <% end %>
 <div class="field">
   <%= form.label :code %>
   <%= form.text_field :code %>
 </div>

 <div class="field">
   <%= form.label :name %>
   <%= form.text_field :name %>
 </div>

 <div class="field">
   <%= form.label :company %>
   <%= form.text_field :company %>
 </div>

 <div class="field">
   <%= form.label :country_code %>
   <%= form.text_field :country_code %>
 </div>

 <div class="field">
   <%= form.label :investment_type_id %>
   <%= form.select :investment_type_id, InvestmentType.all.map {|p| [p.name, p.id]},{}, id: :investment_type_id, class: 'text_field' %>
 </div>

 <div class="actions">
   <%= form.submit %>
 </div>

<% end %>

app/views/investments/edit.html.erb
<h1>Editing Investment</h1>

<%= render 'form', investment: @investment %>

<%= link_to 'Show', @investment %> |
<%= link_to 'Back', investments_path %>

app/views/investments/index.html.erb
<p id="notice"><%= notice %></p>

<% model_class = Investment %>
<h1>Investmentos</h1>
<table>
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:code) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:company) %></th>
      <th><%= model_class.human_attribute_name(:country_code) %></th>
      <th><%= model_class.human_attribute_name(:investment_type_id) %></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @investments.each do |investment| %>
      <tr>
        <td><%= investment.code %></td>
        <td><%= investment.name %></td>
        <td><%= investment.company %></td>
        <td><%= investment.country_code %></td>
        <td><%= investment.investment_type.name %></td>
        <td><%= link_to 'Show', investment %></td>
        <td><%= link_to 'Edit', edit_investment_path(investment) %></td>
        <td><%= link_to 'Destroy', investment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Investment', new_investment_path %>

app/views/investments/new.html.erb
<h1>New Investment</h1>

<%= render 'form', investment: @investment %>

<%= link_to 'Back', investments_path %>

app/views/investments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_investment_path(@investment) %> |
<%= link_to 'Back', investments_path %>