config/routes.rb
Rails.application.routes.draw do 
    
  devise_for :users
  resources :users

  resources :transactions
  resources :investments
  resources :investment_types
  resources :brokers
  resources :transaction_types      
  resources :fundamental_info, only: %i[index new create destroy]

  get 'home/index'
  root to: "home#index"

end

app/controllers/transaction_types_controller.rb
class TransactionTypesController < ApplicationController
  before_action :set_transaction_type, only: %i[ show edit update destroy ]

  # GET /transaction_types or /transaction_types.json
  def index
    @transaction_types = TransactionType.all
  end

  # GET /transaction_types/1 or /transaction_types/1.json
  def show
  end

  # GET /transaction_types/new
  def new
    @transaction_type = TransactionType.new
  end

  # GET /transaction_types/1/edit
  def edit
  end

  # POST /transaction_types or /transaction_types.json
  def create
    @transaction_type = TransactionType.new(transaction_type_params)

    respond_to do |format|
      if @transaction_type.save
        format.html { redirect_to @transaction_type, notice: "Transaction type was successfully created." }
        format.json { render :show, status: :created, location: @transaction_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transaction_types/1 or /transaction_types/1.json
  def update
    respond_to do |format|
      if @transaction_type.update(transaction_type_params)
        format.html { redirect_to @transaction_type, notice: "Transaction type was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transaction_types/1 or /transaction_types/1.json
  def destroy
    @transaction_type.destroy
    respond_to do |format|
      format.html { redirect_to transaction_types_url, notice: "Transaction type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction_type
      @transaction_type = TransactionType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_type_params
      params.require(:transaction_type).permit(:operation, :name, :description)
    end
end

app/helpers/transaction_types_helper.rb
module TransactionTypesHelper
end

app/views/transaction_types/_form.html.erb
<%= form_with(model: transaction_type, local: true) do |form| %>
  <% if transaction_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction_type.errors.count, "error") %> prohibited this transaction_type from being saved:</h2>

      <ul>
      <% transaction_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :operation %>
    <%= form.text_field :operation %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transaction_types/edit.html.erb
<h1>Editing Transaction Type</h1>

<%= render 'form', transaction_type: @transaction_type %>

<%= link_to 'Show', @transaction_type %> |
<%= link_to 'Back', transaction_types_path %>

app/views/transaction_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transaction Types</h1>

<table>
  <thead>
    <tr>
      <th>Operation</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transaction_types.each do |transaction_type| %>
      <tr>
        <td><%= transaction_type.operation %></td>
        <td><%= transaction_type.name %></td>
        <td><%= transaction_type.description %></td>
        <td><%= link_to 'Show', transaction_type %></td>
        <td><%= link_to 'Edit', edit_transaction_type_path(transaction_type) %></td>
        <td><%= link_to 'Destroy', transaction_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction Type', new_transaction_type_path %>

app/views/transaction_types/new.html.erb
<h1>New Transaction Type</h1>

<%= render 'form', transaction_type: @transaction_type %>

<%= link_to 'Back', transaction_types_path %>

app/views/transaction_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Operation:</strong>
  <%= @transaction_type.operation %>
</p>

<p>
  <strong>Name:</strong>
  <%= @transaction_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @transaction_type.description %>
</p>

<%= link_to 'Edit', edit_transaction_type_path(@transaction_type) %> |
<%= link_to 'Back', transaction_types_path %>