config/routes.rb
Rails.application.routes.draw do 
    
  devise_for :users
  resources :users

  resources :transactions
  resources :investments
  resources :investment_types
  resources :brokers
  resources :transaction_types      
  resources :fundamental_info, only: %i[index new create destroy]

  get 'home/index'
  root to: "home#index"

end

app/controllers/investment_types_controller.rb
class InvestmentTypesController < ApplicationController
  before_action :set_investment_type, only: %i[ show edit update destroy ]

  # GET /investment_types or /investment_types.json
  def index
    @investment_types = InvestmentType.all
  end

  # GET /investment_types/1 or /investment_types/1.json
  def show
  end

  # GET /investment_types/new
  def new
    @investment_type = InvestmentType.new
  end

  # GET /investment_types/1/edit
  def edit
  end

  # POST /investment_types or /investment_types.json
  def create
    @investment_type = InvestmentType.new(investment_type_params)

    respond_to do |format|
      if @investment_type.save
        format.html { redirect_to @investment_type, notice: "Investment type was successfully created." }
        format.json { render :show, status: :created, location: @investment_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @investment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investment_types/1 or /investment_types/1.json
  def update
    respond_to do |format|
      if @investment_type.update(investment_type_params)
        format.html { redirect_to @investment_type, notice: "Investment type was successfully updated." }
        format.json { render :show, status: :ok, location: @investment_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @investment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investment_types/1 or /investment_types/1.json
  def destroy
    @investment_type.destroy
    respond_to do |format|
      format.html { redirect_to investment_types_url, notice: "Investment type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investment_type
      @investment_type = InvestmentType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def investment_type_params
      params.require(:investment_type).permit(:name, :description)
    end
end

app/helpers/investment_types_helper.rb
module InvestmentTypesHelper
end

app/views/investment_types/_form.html.erb
<%= form_with(model: investment_type, local: true) do |form| %>
  <% if investment_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(investment_type.errors.count, "error") %> prohibited this investment_type from being saved:</h2>

      <ul>
      <% investment_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/investment_types/edit.html.erb
<h1>Editing Investment Type</h1>

<%= render 'form', investment_type: @investment_type %>

<%= link_to 'Show', @investment_type %> |
<%= link_to 'Back', investment_types_path %>

app/views/investment_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Investment Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @investment_types.each do |investment_type| %>
      <tr>
        <td><%= investment_type.name %></td>
        <td><%= investment_type.description %></td>
        <td><%= link_to 'Show', investment_type %></td>
        <td><%= link_to 'Edit', edit_investment_type_path(investment_type) %></td>
        <td><%= link_to 'Destroy', investment_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Investment Type', new_investment_type_path %>

app/views/investment_types/new.html.erb
<h1>New Investment Type</h1>

<%= render 'form', investment_type: @investment_type %>

<%= link_to 'Back', investment_types_path %>

app/views/investment_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @investment_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @investment_type.description %>
</p>

<%= link_to 'Edit', edit_investment_type_path(@investment_type) %> |
<%= link_to 'Back', investment_types_path %>